name: Test Workflows
on:
  push:
    branches:
      - main
jobs:
  version-zarf-package:
    name: Version Zarf Package
    uses: defenseunicorns/uds-common-workflows/.github/workflows/release-terraform.yml@main
    secrets: inherit
    with:
      command: manifest
      release-type: simple
